# MySQL Database Configuration from Vault
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/onlinesupermarket_user_db
    username: root
    password: shivam2503
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      
  jpa:
    hibernate:
      ddl-auto: update  # Automatically update schema
    show-sql: true      # Show SQL queries in logs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL dialect for Hibernate

# Server Configuration
server:
  port: 8081  # Port for the user service
